name: 'Pull request reviewee reminder action'
description: 'Action to send Github mentions when there are pull requests that has exceeded the lifetime.'
author: 'Kenji Tomita'
inputs:
  github_token:
    required: true
    description: 'GitHub token'
  reminder_message:
    required: true
    description: 'Messages to send to reviewee on Github.'
  pull_request_lifetime_hours:
    required: true
    description: 'This is a lifetime of pull request. If this time is exceeded, a reminder wil be send.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'