name: 'reminder-test'
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1,2,3,4 * * 1-5'
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reminder_message: 'PRがreadyになってから1.2日経過しました。レビュワーと協力してなるべく優先的に作業しましょう。'
          pull_request_lifetime_hours: 0.5